name: Blackduck analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  
permissions:
  contents: read # allows workflow to checkout private repository
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Install dependencies
        run: |
          mvn clean install -P unit-tests  -DskipIntegrationTests
        
      # - name: Download Synopsys Detect Script
      #   run: curl --silent -O https://detect.synopsys.com/detect9.sh
      - name: Download Black Duck Detect Script
        run: curl --silent -O https://detect.blackduck.com/detect9.sh

      - name: Run & analyze BlackDuck Scan
        uses: blackduck-inc/black-duck-security-scan@659a0742e793a093377fab3117b0d90f23b04bfa # v2.9.0
        with:
          blackducksca_url: https://sap.blackducksoftware.com/
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detect_args: >
            --detect.project.name=com.sap.cds.sdm
            --detect.included.detector.types=MAVEN
            --detect.excluded.directories=**/node_modules,**/*test*,**/localrepo,**/target/site,**/*-site.jar,**/samples/**
            --detect.tools=DETECTOR,BINARY_SCAN
            --detect.risk.report.pdf=false
            --logging.level.detect=INFO
        env:
          BLACKDUCKSCA_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
          BLACKDUCKSCA_URL: https://sap.blackducksoftware.com/
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
