name: Deploy

on:
  workflow_dispatch:
    inputs:
      cf_space:
        description: 'Specify the Cloud Foundry space to deploy to'
        required: true
      repository_id:
        description: 'Specify the Repository ID (leave blank if deploying to developcap)'
        required: false

permissions:
  pull-requests: read

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Verify and Checkout Deploy Branch
      - name: Verify and Checkout Deploy Branch
        run: |
          git fetch origin
          if git rev-parse --verify origin/develop_deploy; then
            git checkout develop_deploy
          else
            echo "Branch 'develop_deploy' not found. Please verify the branch name."
            exit 1
          fi

      # Set REPOSITORY_ID
      - name: Set REPOSITORY_ID
        id: set_repository_id
        run: |
          if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
            echo "Using REPOSITORY_ID from secrets"
            echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
          else
            if [ -z "${{ github.event.inputs.repository_id }}" ]; then
              echo "REPOSITORY_ID must be provided for non-developcap spaces"
              exit 1
            else
              echo "Using provided REPOSITORY_ID"
              echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
            fi
          fi

      # Set up Maven authentication
      - name: Set up Maven authentication
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GIT_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Prepare and Deploy to Cloud Foundry
        run: |
          echo "Current Branch......"
          git branch
          pwd
          ls -lart
          cd /home/runner/work/sdm/sdm/cap-notebook/demoapp
          
          # Replace placeholder with actual REPOSITORY_ID value
          sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml

       # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can specify a different version if required

      # Install MTA Build Tool
      - name: Install MTA Build Tool
        run: npm install -g mbt

      
      # Build with Maven
      - name: Build with Maven
        run: mbt build
        #mvn clean install


      # # Build the project
      # - name: Build project
      #   run: mvn clean install

      # # Prepare and Deploy to Cloud Foundry
      # - name: Prepare and Deploy to Cloud Foundry
      #   run: |
      #     cd /sapmnt/home/I355238/actions-runner/_work/sdm/sdm/cap-notebook/demoapp
          
      #     # Replace placeholder with actual REPOSITORY_ID value
      #     sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
          
      #     mbt build

      #     # Install cf CLI plugin
      #     cf install-plugin multiapps -f

      #     # Login to Cloud Foundry again to ensure session is active
      #     cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}

      #     # Deploy the application
      #     cf deploy mta_archives/demoappjava_1.0.0.mtar -f
