name: Deploy and Integration Test

on:
  push:
    branches:
      - fix_integrationtest
  pull_request:
    branches:
      - fix_integrationtest
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  deploy:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Login to Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli
          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

      - name: Build and package
        run: |
          pwd
          ls -lart
          cd sdm
          #mvn clean install -P unit-tests  -DskipIntegrationTests
