#######
name: Main build and snapshot deploy

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.6.3'

on:
  push:
    branches: [ "snapshot_test" ]
  workflow_dispatch:

jobs:
  check-files:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check-changes.outputs.should-run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if pom.xml Changed
        id: check-changes
        run: |
          # Get the list of changed files
          changed_files=$(git diff --name-only origin/${{ github.event.repository.default_branch }} ${{ github.sha }})
          echo "Changed files: $changed_files"
          # Check if pom.xml is in the list of changed files
          if echo "$changed_files" | grep -q "^pom.xml$"; then
            echo "Changes detected in pom.xml"
            echo "should-run=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in files other than pom.xml"
            echo "should-run=true" >> $GITHUB_OUTPUT
          fi
          
  update-version:
    name: Update version
    runs-on: ubuntu-latest
    needs: check-files
    if: needs.check-files.outputs.should-run == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: sapmachine
          cache: maven
          server-id: artifactory
          server-username: ${{ secrets.CAP_DEPLOYMENT_USER }}
          server-password: ${{ secrets.CAP_DEPLOYMENT_PASS }}

      - name: Set up Maven ${{ env.MAVEN_VERSION }}
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: Get Revision
        id: get-revision
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $current_version"
          echo "REVISION=$current_version" >> $GITHUB_ENV
        shell: bash

      - name: Check and Update Version
        if: github.ref == 'refs/heads/snapshot_test'
        id: check-and-update-version
        run: |
          current_version=${{ env.REVISION }}
          # Check if the version already contains '-SNAPSHOT'
          if [[ $current_version != *-SNAPSHOT ]]; then
            echo "Current version does not contain -SNAPSHOT, updating version..."
            # Split version into major, minor, and patch parts
            IFS='.' read -r major minor patch <<< "$(echo $current_version | tr '-' '.')"
            # Increment the patch number
            new_patch=$((patch + 1))
            # Form the new version
            new_version="${major}.${minor}.${new_patch}-SNAPSHOT"
            # Update the <revision> property in pom.xml
            sed -i "s|<revision>.*</revision>|<revision>${new_version}</revision>|" pom.xml
            echo "Updated version to $new_version"
            # Commit the version change
            git config --local user.name "github-actions"
            git config --local user.email "github-actions@github.com"
            git add pom.xml
            git commit -m "Increment version to ${new_version}"
            git push origin HEAD:snapshot_test
          else
            echo "Current version already contains -SNAPSHOT, no update needed."
          fi
          # Export the updated or original version
          updated_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "UPDATED_VERSION=$updated_version" >> $GITHUB_ENV
        shell: bash

      - name: Print Updated Version
        run: |
          echo "Updated version: ${{ env.UPDATED_VERSION }}"
        shell: bash
#######
