name: Multi Tenancy Integration Test 🚀

on:
      
  workflow_dispatch:
    inputs:
      cf_space:
        description: 'Specify the Cloud Foundry space to run integration tests on'
        required: true
        default: developcap

      branch_name:
        description: 'Specify the branch to use for integration tests'
        required: true
        default: develop

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ✅
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Set up Java 17 ☕
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Cloud Foundry CLI and jq 📦
        run: |
          echo "🔧 Installing Cloud Foundry CLI and jq..."
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli jq

      - name: Determine Cloud Foundry Space 🌌
        id: determine_space
        run: |
          if [ "${{ github.event.inputs.cf_space }}" == "developcap" ]; then
            space="${{ secrets.CF_SPACE }}"
          else
            space="${{ github.event.inputs.cf_space }}"
          fi
          echo "🌍 Space determined: $space"
          echo "::set-output name=space::$space"

      - name: Login to Cloud Foundry 🔑
        run: |
          echo "🔄 Logging in to Cloud Foundry using space: ${{ steps.determine_space.outputs.space }}"
          cf login -a ${{ secrets.CF_API }} \
            -u ${{ secrets.CF_USER }} \
            -p ${{ secrets.CF_PASSWORD }} \
            -o ${{ secrets.CF_ORG }} \
            #-s ${{ secrets.CF_SPACE }}
            -s ${{ steps.determine_space.outputs.space }}

      - name: Fetch and Escape Client Details for single tenant 🔍
        id: fetch_credentials
        run: |
          echo "Fetching client details for single tenant..."
          service_instance_guid=$(cf service demoappjava-public-uaa --guid)
          if [ -z "$service_instance_guid" ]; then
            echo "❌ Error: Unable to retrieve service instance GUID"; exit 1;
          fi

          bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
          binding_guid=$(echo "$bindings_response" | jq -r '.resources[0].guid')
          if [ -z "$binding_guid" ]; then
            echo "❌ Error: Unable to retrieve binding GUID"; exit 1;
          fi

          binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")

          clientSecret=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
          if [ -z "$clientSecret" ] || [ "$clientSecret" == "null" ]; then
            echo "❌ Error: clientSecret is not set or is null"; exit 1;
          fi
          escapedClientSecret=$(echo "$clientSecret" | sed 's/\$/\\$/g')
          echo "::add-mask::$escapedClientSecret"

          clientID=$(echo "$binding_details" | jq -r '.credentials.clientid')
          if [ -z "$clientID" ] || [ "$clientID" == "null" ]; then
            echo "❌ Error: clientID is not set or is null"; exit 1;
          fi
          echo "::add-mask::$clientID"

          echo "::set-output name=CLIENT_SECRET::$escapedClientSecret"
          echo "::set-output name=CLIENT_ID::$clientID"
          echo "✅ Client details fetched successfully!"

      - name: Fetch and Escape Client Details for multi tenant 🔍
        id: fetch_credentials_mt
        run: |
          echo "Fetching client details for multi tenant..."
          service_instance_guid=$(cf service bookshop-mt-uaa --guid)
          if [ -z "$service_instance_guid" ]; then
            echo "❌ Error: Unable to retrieve service instance GUID"; exit 1;
          fi

          bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
          binding_guid=$(echo "$bindings_response" | jq -r '.resources[0].guid')
          if [ -z "$binding_guid" ]; then
            echo "❌ Error: Unable to retrieve binding GUID"; exit 1;
          fi

          binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")

          clientSecret_mt=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
          if [ -z "$clientSecret_mt" ] || [ "$clientSecret_mt" == "null" ]; then
            echo "❌ Error: clientSecret_mt is not set or is null"; exit 1;
          fi
          escapedClientSecret_mt=$(echo "$clientSecret_mt" | sed 's/\$/\\$/g')
          echo "::add-mask::$escapedClientSecret_mt"

          clientID_mt=$(echo "$binding_details" | jq -r '.credentials.clientid')
          if [ -z "$clientID_mt" ] || [ "$clientID_mt" == "null" ]; then
            echo "❌ Error: clientID_mt is not set or is null"; exit 1;
          fi
          echo "::add-mask::$clientID_mt"

          echo "::set-output name=CLIENT_SECRET_MT::$escapedClientSecret_mt"
          echo "::set-output name=CLIENT_ID_MT::$clientID_mt"
          echo "✅ Multi-tenant client details fetched successfully!"

      - name: Run integration tests 🎯
        env:
          CLIENT_SECRET: ${{ steps.fetch_credentials.outputs.CLIENT_SECRET }}
          CLIENT_ID: ${{ steps.fetch_credentials.outputs.CLIENT_ID }}
          CLIENT_SECRET_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_SECRET_MT }}
          CLIENT_ID_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_ID_MT }}
        run: |
          echo "🚀 Starting integration tests..."
          set -e
          PROPERTIES_FILE="sdm/src/test/resources/credentials.properties"
          appUrl="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
          appUrlMT="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-bookshop-mt-srv.cfapps.eu12.hana.ondemand.com"
          authUrl="${{ secrets.CAPAUTH_URL }}"
          authUrlMT1="${{ secrets.AUTHURLMT1 }}"
          authUrlMT2="${{ secrets.AUTHURLMT2 }}"
          clientID="${{ env.CLIENT_ID }}"
          clientSecret="${{ env.CLIENT_SECRET }}"
          clientIDMT="${{ env.CLIENT_ID_MT }}"
          clientSecretMT="${{ env.CLIENT_SECRET_MT }}"
          username="${{ secrets.CF_USER }}"
          password="${{ secrets.CF_PASSWORD }}"
          noSDMRoleUsername="${{ secrets.NOSDMROLEUSERNAME }}"
          noSDMRoleUserPassword="${{ secrets.NOSDMROLEUSERPASSWORD }}"

          echo "::add-mask::$clientSecret"
          echo "::add-mask::$clientID"
          echo "::add-mask::$clientSecretMT"
          echo "::add-mask::$clientIDMT"
          echo "::add-mask::$username"
          echo "::add-mask::$password"
          echo "::add-mask::$noSDMRoleUsername"
          echo "::add-mask::$noSDMRoleUserPassword"

          if [ -z "$appUrl" ]; then echo "❌ Error: appUrl is not set"; exit 1; fi
          if [ -z "$appUrlMT" ]; then echo "❌ Error: appUrlMT is not set"; exit 1; fi
          if [ -z "$authUrl" ]; then echo "❌ Error: authUrl is not set"; exit 1; fi
          if [ -z "$authUrlMT1" ]; then echo "❌ Error: authUrlMT1 is not set"; exit 1; fi
          if [ -z "$authUrlMT2" ]; then echo "❌ Error: authUrlMT2 is not set"; exit 1; fi
          if [ -z "$clientID" ]; then echo "❌ Error: clientID is not set"; exit 1; fi
          if [ -z "$clientSecret" ]; then echo "❌ Error: clientSecret is not set"; exit 1; fi
          if [ -z "$clientIDMT" ]; then echo "❌ Error: clientIDMT is not set"; exit 1; fi
          if [ -z "$clientSecretMT" ]; then echo "❌ Error: clientSecretMT is not set"; exit 1; fi
          if [ -z "$username" ]; then echo "❌ Error: username is not set"; exit 1; fi
          if [ -z "$password" ]; then echo "❌ Error: password is not set"; exit 1; fi
          if [ -z "$noSDMRoleUsername" ]; then echo "❌ Error: noSDMRoleUsername is not set"; exit 1; fi
          if [ -z "$noSDMRoleUserPassword" ]; then echo "❌ Error: noSDMRoleUserPassword is not set"; exit 1; fi

          cat > "$PROPERTIES_FILE" <<EOL
          appUrl=$appUrl
          appUrlMT=$appUrlMT
          authUrl=$authUrl
          authUrlMT1=$authUrlMT1
          authUrlMT2=$authUrlMT2
          clientID=$clientID
          clientSecret=$clientSecret
          clientIDMT=$clientIDMT
          clientSecretMT=$clientSecretMT
          username=$username
          password=$password
          noSDMRoleUsername=$noSDMRoleUsername
          noSDMRoleUserPassword=$noSDMRoleUserPassword
          EOL

          echo "🎯 Running Maven integration tests"
          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests
          mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests 
          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests
          mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests
          echo "✅ Integration tests completed!"
