name: Build Cloud Cap Samples Java

on:
  # Trigger the workflow on push to main branch and manual runs.
  push:
    branches: [multi_tenant_deploy]
  workflow_dispatch:

jobs:
  build:
    runs-on: cap-java

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # You can specify a version depending on your needs.

    - name: Install MBT
      run: npm install -g mbt

    - name: Clone the cloud-cap-samples-java repo
      run: git clone --depth 1 --branch main https://github.com/vibhutikumar07/cloud-cap-samples-java.git

    - name: Change directory to cloud-cap-samples-java
      working-directory: cloud-cap-samples-java
      run: pwd # Verifies that we're in the correct directory

    - name: Run mbt build
      working-directory: cloud-cap-samples-java
      run: |
          echo "java version"
          java --version
          mbt build
