name: UnitTestsWithCodeCoverage

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened, synchronize, reopened, auto_merge_enabled]
    
permissions:
  pull-requests: read

jobs:
  unitTests:
    runs-on: cap-java
    strategy:
      matrix:
        java-version: [17]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies and run tests with coverage
      run: |
        mvn clean install

    - name: Upload code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: target/site/jacoco/jacoco.xml
